### PR TITLE
Remove the `@generated` function hack, and instead add `include` statements inside the `__init__()` function

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by chriselrod** [comment]
Interesting, if this works that'd be a nice way to revert back to the old API.

**Comment by chriselrod** [comment]
I think the newer functions approach actually has advantages and could be the recomended way of accessing information.
It could let you redefine constants for testing purposes, e.g.
```julia
VectorizationBase.register_size() = 16
```

**Comment by DilumAluthge** [comment]
BTW, we cannot use `eval` or `@eval` in any of the source code files in the `src/nonprecompileable` folder, because that would break things in any package that depends on VectorizationBase.

So I'll work on fixing that.

**Comment by DilumAluthge** [comment]
> I think the newer functions approach actually has advantages and could be the recomended way of accessing information.
> It could let you redefine constants for testing purposes, e.g.
> 
> ```julia
> VectorizationBase.register_size() = 16
> ```

Sounds good. Let me first get this PR passing tests, and then we can restore those APIs where we want.

**Comment by chriselrod** [comment]
Also, this package hasn't depended on CpuId for a little while now. Not sure how the cpuid file reappeared.

I liked the consolidation of multiple cpuinfo and topology files into one.

**Comment by DilumAluthge** [comment]
> I think the newer functions approach actually has advantages and could be the recomended way of accessing information.
> It could let you redefine constants for testing purposes, e.g.

So, I gave this a try, but if we define functions inside source files that are `include`-d inside `__init__()`, we run into world-age problems.

I think the best approach for redefining the constants is going to be to allow overrides with environment variables at runtime.

**Comment by DilumAluthge** [comment]
> Also, this package hasn't depended on CpuId for a little while now. Not sure how the cpuid file reappeared.

Should be removed now.

**Comment by DilumAluthge** [comment]
> It might be nicer to start from the current master?

So, I tried that, but I could not get the tests to pass.

Let me see if I can get the tests passing on this PR branch.

**Comment by DilumAluthge** [comment]
Also, I just rebased this PR branch on the latest master, so it is up to date with all the changes from master.

**Comment by DilumAluthge** [comment]
@chriselrod I can't figure out how to get the tests to pass on this PR. Can you take a look?

**Comment by DilumAluthge** [comment]
@chriselrod It might just be easier for you to make a brand new PR and follow the approach outlined in this PR, namely to have `include` statements inside `__init__` for the code that should not be precompiled.

Note that, as far as I can tell, you can't define functions in those files, because you will run into world age problems.

**Comment by chriselrod** [comment]
I'm also worried about functions being compiled as looking up globals. Example of what I don't want:
```julia
julia> foo() = X
foo (generic function with 1 method)

julia> foo()
ERROR: UndefVarError: X not defined
Stacktrace:
 [1] foo()
   @ Main ./REPL[1]:1
 [2] top-level scope
   @ REPL[2]:1

julia> const X = 3
3

julia> bar() = X
bar (generic function with 1 method)

julia> caller(f) = f() + 1
caller (generic function with 1 method)

julia> @btime caller(foo)
  15.889 ns (0 allocations: 0 bytes)
4

julia> @btime caller(bar)
  0.015 ns (0 allocations: 0 bytes)
4
```
LLVM:
```llvm
; julia> @code_llvm caller(foo)
;  @ REPL[5]:1 within `caller'
define nonnull {}* @julia_caller_849() {
top:
  %0 = alloca [2 x {}*], align 8
  %.sub = getelementptr inbounds [2 x {}*], [2 x {}*]* %0, i64 0, i64 0
  store {}* inttoptr (i64 140029718302944 to {}*), {}** %.sub, align 8
  %1 = getelementptr inbounds [2 x {}*], [2 x {}*]* %0, i64 0, i64 1
  store {}* inttoptr (i64 140029718302816 to {}*), {}** %1, align 8
  %2 = call nonnull {}* @jl_apply_generic({}* inttoptr (i64 140029813888336 to {}*), {}** nonnull %.sub, i32 2)
  ret {}* %2
}
```
```llvm
; julia> @code_llvm caller(bar)
;  @ REPL[5]:1 within `caller'
define i64 @julia_caller_866() {
top:
  ret i64 4
}
```

**Comment by chriselrod** [comment]
FWIW, on master the functions are currently defined in an order so that tests pass locally when using `--compiled-modules=no`.
Of course, this requires placing a great deal of code after the cpu info.

With some more major reorganization, we may be able to reduce that amount.
But, it's a shame to give up any precompilation at all. Having all the code "preparsed" is fine.

**Comment by DilumAluthge** [comment]
Yeah I think the approach in this PR won't work. I'll post the MWE in #39 on Discourse.

**Comment by DilumAluthge** [comment]
https://discourse.julialang.org/t/global-constants-that-cannot-be-defined-until-runtime-because-they-depend-on-specifics-of-the-cpu-architecture/54077

**Pull request closed without merging**
