### PR TITLE
Try to make VectorizationBase relocatable

### PR DESCRIPTION
**Pull request by chriselrod**
This PR removes `const`s describing the architecture, replacing with with getter functions.

So long as those getter functions aren't precompiled, then I think we should be able to build VectorizationBase into a sysimage, move it elsewhere, and still have things work.

Unfortunately, this may increase latency a bit. But hopefully it solves #31.
I also add `VectorizationBase.num_sockets()` to solve #37.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
There's a test failure?

**Comment by DilumAluthge** [comment]
In addition to making sure the tests pass, we should also make sure that this doesn't have a negative effect on runtime performance, right?

**Comment by chriselrod** [comment]
> we should also make sure that this doesn't have a negative effect on runtime performance, right?

Two ways it can have a negative impact on runtime failure:

1. Bad/generic values accidentally get precompiled somewhere. I'm trying to test for this with
```julia
        for T ∈ (Float32,Float64)
            @test @inferred(VectorizationBase.pick_vector_width(T)) * sizeof(T) == VectorizationBase.register_size() == VectorizationBase.dynamic_register_size()
        end
        for T ∈ (Int8,Int16,Int32,Int64)
            @test @inferred(VectorizationBase.pick_vector_width(T)) * sizeof(T) == VectorizationBase.simd_integer_register_size() == VectorizationBase.dynamic_integer_register_size()
            @test @inferred(VectorizationBase.pick_vector_width(unsigned(T))) * sizeof(unsigned(T)) == VectorizationBase.simd_integer_register_size() == VectorizationBase.dynamic_integer_register_size()
        end
```
and also the "Arch Functions" testset:
```julia
    @time @testset "Arch Functions" begin
        @test VectorizationBase.dynamic_register_size() == @inferred(VectorizationBase.register_size()) == @inferred(VectorizationBase.sregister_size())
        @test VectorizationBase.dynamic_integer_register_size() == @inferred(VectorizationBase.simd_integer_register_size()) == @inferred(VectorizationBase.ssimd_integer_register_size())
        @test VectorizationBase.dynamic_register_count() == @inferred(VectorizationBase.register_count()) == @inferred(VectorizationBase.sregister_count())
        @test VectorizationBase.dynamic_fma_fast() == VectorizationBase.fma_fast()
        @test VectorizationBase.dynamic_has_opmask_registers() == VectorizationBase.has_opmask_registers()
        
        @test VectorizationBase.dynamic_cache_inclusivity() === VectorizationBase.cache_inclusivity()
        
        @test VectorizationBase.Hwloc.histmap(VectorizationBase.Hwloc.topology_load())[Symbol("L", convert(Int, @inferred(VectorizationBase.snum_cache_levels())), "Cache")] > 0
    end
```
The important parts here are that `vector_width` actually matches the dynamic register sizes.
Before I commented out some of the precompile statements, someo f these tests failed.

2. Values no longer known at compile time. This shouldn't be a problem
```julia
julia> @code_typed VectorizationBase.pick_vector_width(Float64)
CodeInfo(
1 ─     return 8
) => Int64

julia> @code_typed VectorizationBase.pick_vector_width_val(Float32, Int32, Float64)
CodeInfo(
1 ─     return Static(8)
) => StaticInt{8}

julia> @code_typed VectorizationBase.pick_vector_width_val(Float32, Int32, Int16)
CodeInfo(
1 ─     return Static(16)
) => StaticInt{16}
```
But it's tested with the `@inferred` on methods turning `StaticInt`s. If these weren't known at compile time, inference would fail.

FWIW. [the docs say](https://docs.julialang.org/en/v1/manual/metaprogramming/):
> Generated functions must not mutate or observe any non-constant global state (including, for example, IO, locks, non-local dictionaries, or using hasmethod). This means they can only read global constants, and cannot have any side effects. In other words, they must be completely pure. 

Which I am violating in this PR. I have a lot of `@generated` functions reading global state that is mutated in `VectorizationBase.__init__()`. But it is constant after the `__init__()` call.

**Comment by DilumAluthge** [comment]
A couple of comments:

1. It would be good to make sure that this doesn't have a negative perf impact in downstream packages. Do you think you could run some Octavian benchmarks with VectorizationBase 0.15.8 versus VectorizationBase 0.16.0 to make sure that the Octavian performance isn't slowed down by this PR?

> Which I am violating in this PR. 

2. This makes me a little nervous. I'd rather avoid breaking the generated functions rules if possible. 

Could you elaborate why those need to be generated functions instead of regular functions?

**Comment by chriselrod** [comment]
Because they're making non-constants constant.

**Comment by DilumAluthge** [comment]
> If the generated function gets compiled before `__init__()` gets called, that is a problem.

I wonder if there is a way we can explicitly prevent this?

**Comment by DilumAluthge** [comment]
On a separate note from this discussion, I've opened https://github.com/chriselrod/VectorizationBase.jl/issues/39. I figure if we can come up with a good MWE, I can spread it on Discourse, etc. and try to get more eyes on the problem.

**Comment by chriselrod** [comment]
> I wonder if there is a way we can explicitly prevent this?

I'm not sure.
While I can fix all my packages, someone else can easily use `precompile` statements (or explicit calls) to precompile them anyway.
They won't be able to precompile and save functions like `VectorizationBase.pick_vector_width`, but they could precompile `pvw`:
```julia
pvw(x) = `VectorizationBase.pick_vector_width(x)`
function __init__()
    precompile(pvw, (Float64,))
end
```

**Pull request merged**
