### PR TITLE
Use Preferences.jl to implement compile-time preferences for overriding topology values

### PR DESCRIPTION
**Pull request by DilumAluthge**
Fixes https://github.com/JuliaLinearAlgebra/Octavian.jl/issues/7

This should not be merged until:
- [x] The Preferences.jl package (https://github.com/JuliaPackaging/Preferences.jl) is registered in the General registry
- [ ] Julia 1.6.0 is released (Preferences.jl requires at least Julia 1.6)

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Demonstration:

```julia
julia> using VectorizationBase

julia> VectorizationBase.CACHE_SIZE
(32768, 262144, 3145728, nothing)

julia> VectorizationBase.set_override("CACHE_SIZE_L1", 1_000)
[ Info: The override has been set. You must restart your Julia session for this change to take effect.

julia> VectorizationBase.set_override("CACHE_SIZE_L2", 2_000)
[ Info: The override has been set. You must restart your Julia session for this change to take effect.

julia> VectorizationBase.set_override("CACHE_SIZE_L3", 3_000)
[ Info: The override has been set. You must restart your Julia session for this change to take effect.

julia> VectorizationBase.set_override("CACHE_SIZE_L4", 4_000)
[ Info: The override has been set. You must restart your Julia session for this change to take effect.
```

Exit Julia and start a new Julia session.

```julia
julia> using VectorizationBase
[ Info: Precompiling VectorizationBase [3d5dd08c-fd9d-11e8-17fa-ed2836048c2f]
[ Info: Using the overrided value for CACHE_SIZE_L1
[ Info: Using the overrided value for CACHE_SIZE_L2
[ Info: Using the overrided value for CACHE_SIZE_L3
[ Info: Using the overrided value for CACHE_SIZE_L4

julia> VectorizationBase.CACHE_SIZE
(1000, 2000, 3000, 4000)
```

Exit Julia and start a new Julia session.

```julia
julia> using VectorizationBase

julia> VectorizationBase.CACHE_SIZE
(1000, 2000, 3000, 4000)
```

Exit Julia and start a new Julia session.

```julia
julia> using VectorizationBase

julia> VectorizationBase.CACHE_SIZE
(1000, 2000, 3000, 4000)

julia> VectorizationBase.delete_override("CACHE_SIZE_L1")
[ Info: The override has been deleted. You must restart your Julia session for this change to take effect.

julia> VectorizationBase.delete_override("CACHE_SIZE_L2")
[ Info: The override has been deleted. You must restart your Julia session for this change to take effect.

julia> VectorizationBase.delete_override("CACHE_SIZE_L3")
[ Info: The override has been deleted. You must restart your Julia session for this change to take effect.

julia> VectorizationBase.delete_override("CACHE_SIZE_L4")
[ Info: The override has been deleted. You must restart your Julia session for this change to take effect.
```

Exit Julia and start a new Julia session.

```julia
julia> using VectorizationBase

julia> VectorizationBase.CACHE_SIZE
(32768, 262144, 3145728, nothing)
```

**Comment by chriselrod** [comment]
Interesting, I'll have to look at this more, but it sounds like it will be useful for debugging.
Computers without AVX2 have been a headache, so mind adding that and `REGISTER_SIZE` as over-loadable options?

**Comment by DilumAluthge** [comment]
>  Computers without AVX2 have been a headache, so mind adding that and `REGISTER_SIZE` as over-loadable options?

Sure. Which constants do those correspond to?

**Comment by chriselrod** [comment]
> > Computers without AVX2 have been a headache, so mind adding that and `REGISTER_SIZE` as over-loadable options?
> 
> Sure. Which constants do those correspond to?

https://github.com/chriselrod/VectorizationBase.jl/blob/master/src/cpu_info_x86_llvm.jl#L14
```julia
    @eval const REGISTER_SIZE = $register_size
    @eval const REGISTER_COUNT = $register_count
```
It also defines a lot of flags in a loop:
```julia
    for ext ∈ features
        @eval const $(Symbol(replace(Base.Unicode.uppercase(ext[2:end]), r"\." => "_"))) = $(first(ext) == '+')
    end
```
E.g., these get defined:
```julia
julia> VectorizationBase.AVX2
true

julia> VectorizationBase.AVX512F # has AVX512 foundation
true

julia> VectorizationBase.AVX512DQ # has AVX512 support for 32 and 64 bit integers
true

julia> VectorizationBase.AVX512IFMA # does not have AVX512 support for (52-bit) integer fmas
false
```
But AVX2 is the one in particular I'd like to turn off, because (a) I don't have access to a computer without it, and (b) it's caused a lot of errors in the past. `(b)` is because AVX2 is gives some 256 bit SIMD integer support. AVX gives 256 bit floating point support, so a computer with AVX will have to choose between using 4x `Int32`, or 2x `Int64`. I try to make it sometimes use the former.

**Comment by DilumAluthge** [comment]
All those flags are bools, right?

**Comment by DilumAluthge** [comment]
What is the type and eltype of `features`?

**Comment by chriselrod** [comment]
Yes, they're all `Bool`s indicating whether or not that feature is supported.
`features` is a `Vector{SubString{String}}`.
```julia
julia> using Libdl

julia> llvmlib = Libdl.dlopen(Base.libllvm_path())
Ptr{Nothing} @0x000055cd0c15cd50

julia> gethostcpufeatures = Libdl.dlsym(llvmlib, :LLVMGetHostCPUFeatures)
Ptr{Nothing} @0x00007f307dc56c30

julia> features_cstring = ccall(gethostcpufeatures, Cstring, ())
Cstring(0x000055cd10d7f640)

julia> features = filter(ext -> (m = match(r"\d", ext); isnothing(m) ? true : m.offset != 2 ), split(unsafe_string(features_cstring), ','));
```
It's only accessible inside that `let` block. That's how llvm provides features, which I then `@eval` into those `Bool`s.

**Comment by DilumAluthge** [comment]
So LLVM gives you e.g. `+avx2`, `-avx512`, and you turn that into `AVX2=true` and `AVX512=false`, respectively?

**Comment by chriselrod** [comment]
Yes.
```julia
julia> function feature_quote(ext)
           :(const $(Symbol(replace(Base.Unicode.uppercase(ext[2:end]), r"\." => "_"))) = $(first(ext) == '+'))
       end
feature_quote (generic function with 1 method)

julia> feature_quote(features[1])
:(const SSE2 = true)

julia> features[1]
"+sse2"
```

**Comment by DilumAluthge** [comment]
I think this is made obsolete now that we use the generated functions hack.

**Comment by chriselrod** [comment]
Given that you have a PR open right now to remove the generated functions hack, I think you already know this, but:

The generated functions hack is not a long term solution. I don't think the compiler folks make any guarantees about things like that not precompiling, and I'm sure they want to get a lot more aggressive in how much gets precompiled in the future, meaning that approach is not future proof.
So we do want something else.

**Pull request closed without merging**
