### PR TITLE
Use getter functions to specify system info and `@eval` in `__init__()` to correct if misspecified

### PR DESCRIPTION
**Pull request by chriselrod**
This PR is following the strategy outlined by staticfloat [here](https://discourse.julialang.org/t/global-constants-that-cannot-be-defined-until-runtime-because-they-depend-on-specifics-of-the-cpu-architecture/54077/3?u=elrod).

VectorizationBase still relies on a great deal of `@generated` functions. These now no longer access global constants or directly query system information themselves (which would risk those values getting baked into the `@generated` function).
Instead, they take arguments describing system information with types.
E.g.,
```julia
julia> using VectorizationBase

julia> VectorizationBase.register_size()
static(64)

julia> typeof(ans)
StaticInt{64}
```
`register_size()` will be redefined if the value is incorrect, thus all methods calling `register_size` will recompile to reflect the updated value, and then call the `@generated` functions with new parameter values.

### CODE REVIEW

**Comment by chriselrod** [comment]
fixes #39

**Comment by DilumAluthge** [comment]
Fixes https://github.com/JuliaLinearAlgebra/Octavian.jl/issues/7?

**Comment by DilumAluthge** [comment]
Also, edit the title to reflect we're no longer using Preferences?

**Comment by DilumAluthge** [comment]
Also, you can still run CI on Julia 1.

**Comment by chriselrod** [comment]
Yes, using functions makes it a lot easier to spoof and will cause dependent functions to recompile.

This does have the limitation that we cannot actually query cpu information inside `@generated` functions.
For this reason, I follow the pattern of making the `@generated` pieces a core, with a wrapper that calls the query functions and passes the results as type information.

For this reason, all the query functions return their result as a type, for easy use in the generated functions.

**Pull request merged**
