### PR TITLE
Prevent generated functions from being compiled before `__init__()` has been called

### PR DESCRIPTION
**Pull request by DilumAluthge**
This is truly evil, and we should not merge it. I'm just curious if it will even work.

### CODE REVIEW

**Comment by chriselrod** [comment]
Hmm, good idea!
Yeah, we could put checks like that in all the generated functions.

**Comment by DilumAluthge** [comment]
It feels wrong 😂 

In order to deal with the problem of our generated functions reading global mutable state, we.... make them read even more global mutable state

**Comment by chriselrod** [comment]
In for a penny...

But this way, we'd at least know if something went wrong.

**Comment by chriselrod** [comment]
I'd merge the PR if you want to add those checks to all the `@generated` functions specifying hardware attributes.

**Comment by DilumAluthge** [comment]
Can you list which `@generated` functions those are? Then I'll add this check to all of them.

**Comment by chriselrod** [comment]
Three files:
[cache_inclusivity](https://github.com/chriselrod/VectorizationBase.jl/blob/master/src/cache_inclusivity.jl)
[cpu_info](https://github.com/chriselrod/VectorizationBase.jl/blob/master/src/cpu_info.jl)
[topology](https://github.com/chriselrod/VectorizationBase.jl/blob/master/src/topology.jl)

**Comment by DilumAluthge** [comment]
Take a look and see if I got them all.

**Comment by chriselrod** [comment]
Looks like it, awesome. I'll merge when green.

**Comment by DilumAluthge** [comment]
It's a bit of a pain. Official docs: https://docs.github.com/en/github/administering-a-repository/managing-auto-merge-for-pull-requests-in-your-repository

The steps:
1. Go to the repo and click the Settings tab, which brings you to e.g. https://github.com/JuliaLinearAlgebra/Octavian.jl/settings
2. Click on branches, which brings you to e.g. https://github.com/JuliaLinearAlgebra/Octavian.jl/settings/branches
3. Make sure you have added `master` as a protected branch. If you have not, instructions are here: https://docs.github.com/en/github/administering-a-repository/about-protected-branches and https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule
4. In the row that says `master - Currently applies to 1 branch` click on the Edit button.
5. Check this checkbox: `Require status checks to pass before merging `
6. In the `Status checks found in the last week for this repository` section, you need to click the box next to all the statuses that you want auto-merge to wait for.

**Pull request merged**
