### PR TITLE
Not Fast

### PR DESCRIPTION
**Pull request by chriselrod**
I'll merge shortly.

### CODE REVIEW

**Comment by chriselrod** [comment]
@JeffreySarnoff @ffevotte @dzhang314
Thought I'd ask about what flags to use for default arithmetic.
Right now it is:
```julia
julia> using VectorizationBase

julia> VectorizationBase.fast_flags(false)
"nsz contract"

julia> vx = Vec(ntuple(_ -> 10randn(), VectorizationBase.pick_vector_width_val(Float64))...)
Vec{8,Float64}<6.381310591506147, 5.05098160355799, 19.108264674413483, 4.126167596790146, 8.706923468015798, -20.24830645218576, 19.40787010936436, 24.012391289475637>

julia> @code_llvm debuginfo=:none vx + vx
```
```llvm
define void @"julia_+_852"([1 x <8 x double>]* noalias nocapture sret %0, [1 x <8 x double>]* nocapture nonnull readonly align 16 dereferenceable(64) %1, [1 x <8 x double>]* nocapture nonnull readonly align 16 dereferenceable(64) %2) {
top:
  %3 = getelementptr inbounds [1 x <8 x double>], [1 x <8 x double>]* %1, i64 0, i64 0
  %4 = getelementptr inbounds [1 x <8 x double>], [1 x <8 x double>]* %2, i64 0, i64 0
  %5 = load <8 x double>, <8 x double>* %3, align 16
  %6 = load <8 x double>, <8 x double>* %4, align 16
  %res.i = fadd nsz contract <8 x double> %5, %6
  %7 = getelementptr inbounds [1 x <8 x double>], [1 x <8 x double>]* %0, i64 0, i64 0
  store <8 x double> %res.i, <8 x double>* %7, align 64
  ret void
}
```
Note the `fadd nsz contract`.

These still allow some optimizations, e.g. contraction (the actual contraction happens in the target-specific backend, so we won't see it until `@code_native`:
```
julia> mymuladd(a,b,c) = a * b + c
mymuladd (generic function with 1 method)
```
```asm
julia> @code_native syntax=:intel debuginfo=:none mymuladd(vx, vx, vx)
        .text
        mov     rax, rdi
        vmovupd zmm0, zmmword ptr [rsi]
        vmovupd zmm1, zmmword ptr [rdx]
        vfmadd213pd     zmm1, zmm0, zmmword ptr [rcx] # zmm1 = (zmm0 * zmm1) + mem
        vmovapd zmmword ptr [rdi], zmm1
        vzeroupper
        ret
        nop
```
The `*` and `+` have contracted into `vfmadd213pd`.

This also lets it remove the addition in `a + b + 0` :
```julia
julia> mymul(a,b) = a * b + zero(a)
mymul (generic function with 1 method)

julia> @code_native syntax=:intel debuginfo=:none mymul(vx,vx)
```
```asm
        .text
        mov     rax, rdi
        vmovupd zmm0, zmmword ptr [rsi]
        vmulpd  zmm0, zmm0, zmmword ptr [rdx]
        vmovapd zmmword ptr [rdi], zmm0
        vzeroupper
        ret
        nop     dword ptr [rax]
```
Note we have a `vmulpd` wihout any additions, but without the flags:
```julia
julia> @code_native syntax=:intel debuginfo=:none mymul(1.2, 2.3)
```
```asm
        .text
        vmulsd  xmm0, xmm0, xmm1
        vxorpd  xmm1, xmm1, xmm1
        vaddsd  xmm0, xmm0, xmm1
        ret
        nop     dword ptr [rax]
```
Same story if we use a specific `muladd`:
```julia
julia> mymul2(a,b) = muladd(a, b, zero(a))
mymul2 (generic function with 1 method)

julia> @code_native syntax=:intel debuginfo=:none mymul2(1.2, 2.3)
```
```asm
        .text
        vxorpd  xmm2, xmm2, xmm2
        vfmadd213sd     xmm0, xmm1, xmm2        # xmm0 = (xmm1 * xmm0) + xmm2
        ret
        nop     word ptr [rax + rax]
```
`vxorpd` to create a zero before `vfmadd`ing it looks a little silly.
```julia
julia> @code_native syntax=:intel debuginfo=:none mymul2(vx, vx)
```
```asm
        .text
        mov     rax, rdi
        vmovupd zmm0, zmmword ptr [rsi]
        vmulpd  zmm0, zmm0, zmmword ptr [rdx]
        vmovapd zmmword ptr [rdi], zmm0
        vzeroupper
        ret
        nop     dword ptr [rax]
```

Note that using `-zero(a)` does allow the compiler to eliminate the addition of zero, but if it is not eliminated, it is more expensie to create as it isn't simply a `vxorpd`. Meaning your codegen logic would have to be a bit more complex.
This mostly matters for loops that may or may not be unrolled, where if they aren't unrolled you want to create zeros efficiently for accumulating into, and if they are unrolled you'd rather have those zeros get eliminated.

Also, all the `vmov(a/u)pd`s will be removed so long as the vectors do not actually cross a (non-inlined) function boundary.  If you do want to pass them around between functions that aren't inlined, consider `data(vx)` to strip the struct wrapper, and `Vec(x)` to re-add, e.g.:
```julia
julia> mymuladdv2(a,b,c) = VectorizationBase.data(Vec(a) * Vec(b) + Vec(c))
mymuladdv2 (generic function with 1 method)

julia> @code_native syntax=:intel debuginfo=:none mymuladdv2(VectorizationBase.data.((vx, vx, vx))...)
```
```asm
        .text
        vfmadd213pd     zmm0, zmm1, zmm2        # zmm0 = (zmm1 * zmm0) + zmm2
        ret
        nop     word ptr [rax + rax]
```
In most use cases they won't be passing such boundaries, but it's something to consider given the absolutely massive size of the unrolled code of some of the compensated arithmetic kernels.

@haampie thought that `nsz contract` would be fine, but thought I'd double check with others.
I'll probably merge this soon, but can always change in a later commit now that it does have separate fast/not fast versions.

**Comment by JeffreySarnoff** [comment]
thanks

**Comment by JeffreySarnoff** [comment]
I did not run the tests, but looking at the group that fails and the fact that three tests fail suggests these `Base.FastMath.abs2_fast, Base.FastMath.inv_fast, Base.FastMath.sub_fast` are generating errors.

**Comment by chriselrod** [comment]
It was `inv_fast`, failing here:
```julia
for f ∈ [
    -, abs, inv, floor, ceil, trunc, round, sqrt ∘ abs, VectorizationBase.relu, abs2,
    Base.FastMath.abs2_fast, Base.FastMath.sub_fast
]
        @test tovector(@inferred(f(v))) == map(f, x)
end
```
Note the exact equality check, `==`.
I didn't notice that when I added `inv_fast` to the list (now removed above).

The default `inv` is basically implemented as `inv(x) = one(x) / x`.
I implemented `inv_fast` using an approximate reciprocal, followed by 1 (`Float32`) or 2 (`Float64`) Newton iterations to correct the accuracy problems:
```julia
julia> vx64 = Vec(ntuple(_ -> 10randn(), VectorizationBase.pick_vector_width_val(Float64))...)
Vec{8,Float64}<-3.085680137472824, 3.6779578555175467, 2.1842622872088984, -4.870055918620315, 8.476002936431025, -1.9428794063865429, 12.910213045440644, 2.3704258402405918>

julia> vx32 = Vec(ntuple(_ -> 10randn(Float32), VectorizationBase.pick_vector_width_val(Float32))...)
Vec{16,Float32}<-10.782653f0, 9.0236845f0, -7.69788f0, 3.1359708f0, 12.666565f0, 42.83398f0, -10.924363f0, 5.717588f0, -23.760254f0, -3.0951114f0, -11.202073f0, 2.7761073f0, 4.955823f0, -1.1981986f0, -7.958027f0, -1.8709383f0>

julia> @code_native syntax=:intel debuginfo=:none Base.FastMath.inv_fast(vx32)
        .text
        mov     rax, rdi
        vmovups zmm0, zmmword ptr [rsi]
        vrcp14ps        zmm1, zmm0
        movabs  rcx, offset .rodata.cst4
        vfnmadd213ps    zmm0, zmm1, dword ptr [rcx]{1to16} # zmm0 = -(zmm1 * zmm0) + mem
        vmulps  zmm0, zmm1, zmm0
        vmovaps zmmword ptr [rdi], zmm0
        vzeroupper
        ret
        nop

julia> @code_native syntax=:intel debuginfo=:none Base.FastMath.inv_fast(vx64)
        .text
        mov     rax, rdi
        vmovupd zmm0, zmmword ptr [rsi]
        vrcp14pd        zmm1, zmm0
        movabs  rcx, offset .rodata.cst8
        vbroadcastsd    zmm2, qword ptr [rcx]
        vmovapd zmm3, zmm1
        vfnmadd213pd    zmm3, zmm0, zmm2        # zmm3 = -(zmm0 * zmm3) + zmm2
        vmulpd  zmm1, zmm1, zmm3
        vfnmadd213pd    zmm0, zmm1, zmm2        # zmm0 = -(zmm1 * zmm0) + zmm2
        vmulpd  zmm0, zmm1, zmm0
        vmovapd zmmword ptr [rdi], zmm0
        vzeroupper
        ret
        nop     word ptr [rax + rax]
```
But it still isn't exact.

Trying:
```julia
julia> using VectorizationBase, StatsBase, LinearAlgebra

julia> include(joinpath(pkgdir(VectorizationBase), "test", "testsetup.jl"))
mini (generic function with 2 methods)

julia> function randapprox(::Type{T}) where {T}
           x = Vec(ntuple(_ -> 10randn(T), VectorizationBase.pick_vector_width_val(T))...)
           via = @fastmath inv(x)
           vir = inv(x)
           relapprox(tovector(via), tovector(vir))
       end
randapprox (generic function with 1 method)

julia> function relapprox(x::AbstractVector{T},y) where {T}
           t = max(norm(x),norm(y)) * eps(T)
           n = norm(x .- y)
           n / t
       end
relapprox (generic function with 1 method)

julia> f32t = map(_ -> randapprox(Float32), 1:1_000_000);

julia> f64t = map(_ -> randapprox(Float64), 1:1_000_000);

julia> summarystats(f64t)
Summary Stats:
Length:         1000000
Missing Count:  0
Mean:           0.343880
Minimum:        0.000000
1st Quartile:   0.114391
Median:         0.316866
3rd Quartile:   0.544607
Maximum:        0.999627


julia> summarystats(f32t)
Summary Stats:
Length:         1000000
Missing Count:  0
Mean:           0.249317
Minimum:        0.000000
1st Quartile:   0.063032
Median:         0.175763
3rd Quartile:   0.400251
Maximum:        0.999345
```
These are the distributions of `rtol` relative to `eps(T)`. On computers with AVX512, the `rtol` does appear to be less than `eps(T)`, at least out of a million samples.
The approximation is less accurate without AVX512, so I'll have to test that specifically later. For now, I'm using `4eps(T)` as the maximum acceptable tolerance.

The initial reciprical approximation's maximum error is 6x higher without AVX512, but I don't know what this looks like after the Newton iteration (singular, because AVX512 is needed for `Float64` support).

**Comment by chriselrod** [comment]
Well, the exact equality check just failed above a few times, even without `inv_fast` in there:
```julia
 Unary Functions: Test Failed at /home/runner/work/VectorizationBase.jl/VectorizationBase.jl/test/runtests.jl:443
  Expression: tovector(#= /home/runner/work/VectorizationBase.jl/VectorizationBase.jl/test/runtests.jl:443 =# @inferred(f(vi))) == map(f, xi)
   Evaluated: [-6.323544271832987e-19, 1.4683007926363305e-18, -3.206035749069376e-19, -2.0491798157081646e-19, 3.4978903945187804e-19, -4.878143095932734e-19, 1.089028804906855e-19, 1.403282941411715e-18, 2.4794644903790363e-19, -1.3988711616498127e-19  …  -1.1867893285361477e-18, -1.5408667382381052e-19, -2.203758086667756e-19, 2.303206336276823e-19, -1.7879371288685158e-19, -2.317279666515642e-19, 1.2424187734676259e-19, -2.0636777179038464e-19, -1.3550264296732994e-19, 1.478478488462815e-19] == [-6.323544271832986e-19, 1.4683007926363305e-18, -3.206035749069376e-19, -2.0491798157081643e-19, 3.4978903945187804e-19, -4.878143095932734e-19, 1.089028804906855e-19, 1.403282941411715e-18, 2.4794644903790363e-19, -1.3988711616498127e-19  …  -1.1867893285361477e-18, -1.5408667382381052e-19, -2.203758086667756e-19, 2.303206336276823e-19, -1.787937128868516e-19, -2.3172796665156413e-19, 1.2424187734676259e-19, -2.0636777179038464e-19, -1.3550264296732994e-19, 1.478478488462815e-19]
```
So it looks like another of these is not exact.

**Comment by JeffreySarnoff** [comment]
great, please allow this new version (in master) to be accepted by LoopVectorization#master when you get a chance.

**Comment by chriselrod** [comment]
I've updated it locally, and will push once a new version of SLEEFPirates.jl gets tagged.

**Comment by haampie** [comment]
Thanks @chriselrod  :)

**Pull request merged**
